# Generated by Django 5.2.4 on 2025-07-25 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_almacen', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('direccion_tributaria', models.CharField(blank=True, max_length=255)),
                ('comuna', models.CharField(blank=True, choices=[('Seleccione la comuna', 'Seleccione la comuna'), ('Alhué', 'Alhué'), ('Buín', 'Buín'), ('Calera de Tango', 'Calera de Tango'), ('Cerrillos', 'Cerrillos'), ('Cerro Navia', 'Cerro Navia'), ('Colina', 'Colina'), ('Conchalí', 'Conchalí'), ('Curacaví', 'Curacaví'), ('El Bosque', 'El Bosque'), ('El Monte', 'El Monte'), ('Estación Central', 'Estación Central'), ('Huechuraba', 'Huechuraba'), ('Independencia', 'Independencia'), ('Isla de Maipo', 'Isla de Maipo'), ('La Cisterna', 'La Cisterna'), ('La Florida', 'La Florida'), ('La Granja', 'La Granja'), ('La Pintana', 'La Pintana'), ('La Reina', 'La Reina'), ('Lampa', 'Lampa'), ('Las Condes', 'Las Condes'), ('Lo Barnechea', 'Lo Barnechea'), ('Lo Espejo', 'Lo Espejo'), ('Lo Prado', 'Lo Prado'), ('Macul', 'Macul'), ('Maipú', 'Maipú'), ('María Pinto', 'María Pinto'), ('Melipilla', 'Melipilla'), ('Ñuñoa', 'Ñuñoa'), ('Padre Hurtado', 'Padre Hurtado'), ('Paine', 'Paine'), ('Pedro Aguirre Cerda', 'Pedro Aguirre Cerda'), ('Peñalolén', 'Peñalolén'), ('Peñaflor', 'Peñaflor'), ('Pirque', 'Pirque'), ('Providencia', 'Providencia'), ('Pudahuel', 'Pudahuel'), ('Puente Alto', 'Puente Alto'), ('Quilicura', 'Quilicura'), ('Quinta Normal', 'Quinta Normal'), ('Recoleta', 'Recoleta'), ('Renca', 'Renca'), ('San Bernardo', 'San Bernardo'), ('San Joaquín', 'San Joaquín'), ('San José de Maipo', 'San José de Maipo'), ('San Miguel', 'San Miguel'), ('San Pedro', 'San Pedro'), ('San Ramón', 'San Ramón'), ('Santiago', 'Santiago'), ('Talagante', 'Talagante'), ('Til Til', 'Til Til'), ('Vitacura', 'Vitacura')], default='Seleccione la comuna', max_length=100)),
                ('run_representante', models.CharField(max_length=12)),
                ('inicio_actividades', models.DateField()),
                ('nivel_venta_uf', models.CharField(blank=True, max_length=100)),
                ('giro_negocio', models.CharField(max_length=100)),
                ('tipo_sociedad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlanSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('FREE', 'Gratuito'), ('BASIC', 'Básico'), ('PREMIUM', 'Premium')], max_length=50, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
                ('max_productos', models.IntegerField(default=0, help_text='Número máximo de productos. 0 para ilimitado.')),
                ('max_almacenes', models.IntegerField(default=1, help_text='Número máximo de almacenes. 1 para gratuito.')),
                ('soporte_prioritario', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Almacenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('snombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('sapellido', models.CharField(max_length=25)),
                ('run', models.CharField(max_length=12, unique=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('comuna', models.CharField(blank=True, choices=[('Seleccione la comuna', 'Seleccione la comuna'), ('Alhué', 'Alhué'), ('Buín', 'Buín'), ('Calera de Tango', 'Calera de Tango'), ('Cerrillos', 'Cerrillos'), ('Cerro Navia', 'Cerro Navia'), ('Colina', 'Colina'), ('Conchalí', 'Conchalí'), ('Curacaví', 'Curacaví'), ('El Bosque', 'El Bosque'), ('El Monte', 'El Monte'), ('Estación Central', 'Estación Central'), ('Huechuraba', 'Huechuraba'), ('Independencia', 'Independencia'), ('Isla de Maipo', 'Isla de Maipo'), ('La Cisterna', 'La Cisterna'), ('La Florida', 'La Florida'), ('La Granja', 'La Granja'), ('La Pintana', 'La Pintana'), ('La Reina', 'La Reina'), ('Lampa', 'Lampa'), ('Las Condes', 'Las Condes'), ('Lo Barnechea', 'Lo Barnechea'), ('Lo Espejo', 'Lo Espejo'), ('Lo Prado', 'Lo Prado'), ('Macul', 'Macul'), ('Maipú', 'Maipú'), ('María Pinto', 'María Pinto'), ('Melipilla', 'Melipilla'), ('Ñuñoa', 'Ñuñoa'), ('Padre Hurtado', 'Padre Hurtado'), ('Paine', 'Paine'), ('Pedro Aguirre Cerda', 'Pedro Aguirre Cerda'), ('Peñalolén', 'Peñalolén'), ('Peñaflor', 'Peñaflor'), ('Pirque', 'Pirque'), ('Providencia', 'Providencia'), ('Pudahuel', 'Pudahuel'), ('Puente Alto', 'Puente Alto'), ('Quilicura', 'Quilicura'), ('Quinta Normal', 'Quinta Normal'), ('Recoleta', 'Recoleta'), ('Renca', 'Renca'), ('San Bernardo', 'San Bernardo'), ('San Joaquín', 'San Joaquín'), ('San José de Maipo', 'San José de Maipo'), ('San Miguel', 'San Miguel'), ('San Pedro', 'San Pedro'), ('San Ramón', 'San Ramón'), ('Santiago', 'Santiago'), ('Talagante', 'Talagante'), ('Til Til', 'Til Til'), ('Vitacura', 'Vitacura')], default='Seleccione la comuna', max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='LoteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField(db_index=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_de_empresa', to='inventario.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='OfertaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total_productos', models.PositiveIntegerField(default=0)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=50)),
                ('nombre', models.CharField(db_index=True, max_length=100)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('categoria', models.CharField(choices=[('Seleccione la categoría', 'Seleccione la categoría'), ('Alimentos Secos', 'Alimentos Secos'), ('Aliemntos Frescos', 'Alimentos Frescos'), ('Bebidas', 'Bebidas'), ('Lacteos', 'Lácteos'), ('Congelados', 'Congelados'), ('Dulcería & Confitería', 'Dulcería & Confitería'), ('Mascotas', 'Mascotas'), ('Belleza', 'Belleza'), ('Aseo del Hogar', 'Aseo del Hogar'), ('Aseo Personal', 'Aseo Personal'), ('Misceláneos', 'Misceláneos'), ('Papelería & Oficina', 'Papelería & Oficina'), ('Electrónica Menor', 'Electrónica Menor'), ('Temporada / Festivos', 'Temporada / Festivos'), ('Fiambres', 'Fiambres')], db_index=True, default='Seleccione la categoría', max_length=50)),
                ('dramage', models.IntegerField(default=0)),
                ('unidad_medida', models.CharField(choices=[('Seleccione la unidad', 'Seleccione la unidad'), ('Unidad', 'und'), ('Litro', 'lt'), ('Kilogramo', 'kg'), ('Gramo', 'gm'), ('Milimetro', 'ml'), ('Centímetro', 'cm'), ('Caja', 'cj'), ('Paquete', 'pqt'), ('Docena', 'dz'), ('Bolsa', 'bs'), ('Centimetro cúbico', 'cc')], default='Seleccione la unidad', max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('empresas', models.ManyToManyField(related_name='productos_ofrecidos', through='inventario.OfertaProducto', to='inventario.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='ofertaproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_retirada', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.loteproducto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
        migrations.AddField(
            model_name='loteproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventario.producto'),
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.ordenventa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='SuscripcionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='inventario.empresa')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.plansuscripcion')),
            ],
            options={
                'verbose_name_plural': 'Suscripciones de Usuarios',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ofertaproducto',
            unique_together={('producto', 'empresa')},
        ),
        migrations.AlterUniqueTogether(
            name='loteproducto',
            unique_together={('producto', 'empresa', 'fecha_vencimiento')},
        ),
    ]
