# Generated by Django 5.2.4 on 2025-07-31 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='almaceneros',
        ),
        migrations.AddField(
            model_name='almacenero',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='almaceneros', to='inventario.empresa'),
        ),
    ]
