# Generated by Django 5.2.2 on 2025-06-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('Seleccione la unidad', 'Seleccione la unidad'), ('Unidad', 'und'), ('Litro', 'lt'), ('Kilogramo', 'kg'), ('Gramo', 'gm'), ('Milimetro', 'ml'), ('Centímetro', 'cm'), ('Caja', 'cj'), ('Paquete', 'pqt'), ('Docena', 'dz'), ('Bolsa', 'bs'), ('Centimetro cúbico', 'cc')], default='Seleccione la unidad', help_text='Seleccione la unidad de medida del producto.', max_length=50),
        ),
    ]
