# Generated by Django 5.2.2 on 2025-06-20 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_producto_unidad_medida'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
