# Generated by Django 5.2.3 on 2025-07-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_almacenero_comuna_alter_empresa_comuna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
        migrations.AlterField(
            model_name='loteproducto',
            name='fecha_vencimiento',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Seleccione la categoría', 'Seleccione la categoría'), ('Alimentos Secos', 'Alimentos Secos'), ('Aliemntos Frescos', 'Alimentos Frescos'), ('Bebidas', 'Bebidas'), ('Lacteos', 'Lácteos'), ('Congelados', 'Congelados'), ('Dulcería & Confitería', 'Dulcería & Confitería'), ('Mascotas', 'Mascotas'), ('Belleza', 'Belleza'), ('Aseo del Hogar', 'Aseo del Hogar'), ('Aseo Personal', 'Aseo Personal'), ('Misceláneos', 'Misceláneos'), ('Papelería & Oficina', 'Papelería & Oficina'), ('Electrónica Menor', 'Electrónica Menor'), ('Temporada / Festivos', 'Temporada / Festivos'), ('Fiambres', 'Fiambres')], db_index=True, default='Seleccione la categoría', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('Seleccione la unidad', 'Seleccione la unidad'), ('Unidad', 'und'), ('Litro', 'lt'), ('Kilogramo', 'kg'), ('Gramo', 'gm'), ('Milimetro', 'ml'), ('Centímetro', 'cm'), ('Caja', 'cj'), ('Paquete', 'pqt'), ('Docena', 'dz'), ('Bolsa', 'bs'), ('Centimetro cúbico', 'cc')], default='Seleccione la unidad', max_length=50),
        ),
    ]
