# Generated by Django 5.2.2 on 2025-06-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_delete_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacenero',
            name='correo',
            field=models.EmailField(default='sincorreo@focal.cl', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
