# Generated by Django 5.1.4 on 2025-05-22 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_empresa_rename_rut_almacenero_run_almacenero_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('FREE', 'Gratuito'), ('BASIC', 'Básico'), ('PREMIUM', 'Premium')], max_length=50, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
                ('max_productos', models.IntegerField(default=0, help_text='Número máximo de productos. 0 para ilimitado.')),
                ('max_almacenes', models.IntegerField(default=1, help_text='Número máximo de almacenes. 1 para gratuito.')),
                ('soporte_prioritario', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SuscripcionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='inventario.empresa')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.plansuscripcion')),
            ],
            options={
                'verbose_name_plural': 'Suscripciones de Usuarios',
            },
        ),
    ]
