# Generated by Django 5.2.4 on 2025-07-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_producto_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='dramage',
            field=models.IntegerField(default=0),
        ),
    ]
