# Generated by Django 5.2.4 on 2025-08-04 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_almacenero_comuna_alter_almacenero_region_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='almacenero',
            old_name='apellido',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='almacenero',
            old_name='nombre',
            new_name='nombres',
        ),
        migrations.RemoveField(
            model_name='almacenero',
            name='sapellido',
        ),
        migrations.RemoveField(
            model_name='almacenero',
            name='snombre',
        ),
    ]
