# Generated by Django 5.2.4 on 2025-08-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_rename_apellido_almacenero_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
