# Generated by Django 5.2.4 on 2025-08-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_empresa_razon_social'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ofertaproducto',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('abarrotes', 'Abarrotes'), ('frutas_verduras', 'Frutas y Verduras'), ('carniceria', 'Carnicería'), ('panaderia', 'Panadería'), ('lacteos_huevos', 'Lácteos y Huevos'), ('bebidas', 'Bebidas'), ('snacks', 'Snacks y Dulces'), ('congelados', 'Congelados'), ('limpieza', 'Artículos de Limpieza'), ('personal', 'Cuidado Personal'), ('licores', 'Licores'), ('embutidos', 'Embutidos'), ('pollo_granel', 'Pollo al Granel'), ('especias', 'Especias y Condimentos'), ('mascotas', 'Mascotas'), ('hogar', 'Artículos de Hogar'), ('reposteria', 'Repostería y Postres')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(blank=True, choices=[('un', 'Unidad'), ('kg', 'Kilogramo'), ('g', 'Gramo'), ('l', 'Litro'), ('ml', 'Mililitro'), ('mg', 'Miligramo'), ('cm', 'Centímetro')], max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='ofertaproducto',
            constraint=models.UniqueConstraint(fields=('producto', 'empresa'), name='unique_producto_empresa'),
        ),
    ]
