# Generated by Django 5.2.1 on 2025-06-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_producto_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('ALIMENTOS', 'Alimentos'), ('BEBIDAS', 'Bebidas'), ('ELECTRONICA', 'Electrónica'), ('HOGAR', 'Hogar'), ('LIMPIEZA', 'Limpieza'), ('ROPA', 'Ropa'), ('OFICINA', 'Oficina'), ('DEPORTES', 'Deportes'), ('JUGUETES', 'Juguetes'), ('FERRETERIA', 'Ferretería'), ('OTRO', 'Otro')], default='OTRO', help_text='Seleccione la categoría del producto.', max_length=50),
        ),
    ]
