# Generated by Django 5.2.1 on 2025-06-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Seleccione la categoría', 'Seleccione la categoría'), ('Alimentos', 'Alimentos'), ('Bebidas', 'Bebidas'), ('Salud', 'Salud'), ('Electrónica', 'Electrónica'), ('Belleza', 'Belleza'), ('Hogar', 'Hogar'), ('Limpieza', 'Limpieza')], default='Seleccione la categoría', help_text='Seleccione la categoría del producto.', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('Seleccione la unidad', 'Seleccione la unidad'), ('Litro', 'Litro'), ('Kilogramo', 'Kilogramo'), ('Gramo', 'Gramo'), ('Mililitro', 'Mililitro'), ('Centímetro', 'Centímetro'), ('Caja', 'Caja'), ('Paquete', 'Paquete'), ('Docena', 'Docena')], default='Seleccione la unidad', help_text='Seleccione la unidad de medida del producto.', max_length=50),
        ),
    ]
