# Generated by Django 5.2.4 on 2025-08-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_proveedor_loteproducto_precio_compra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='sitio_web',
        ),
    ]
