# Generated by Django 5.2.4 on 2025-08-04 21:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_remove_proveedor_sitio_web'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loteproducto',
            options={'ordering': ['-fecha_ingreso'], 'verbose_name': 'Lote de Producto', 'verbose_name_plural': 'Lotes de Productos'},
        ),
        migrations.RemoveField(
            model_name='ofertaproducto',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='ofertaproducto',
            name='precio_venta',
        ),
        migrations.AddField(
            model_name='loteproducto',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ofertaproducto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ofertaproducto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ofertaproducto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ofertaproducto',
            name='precio_venta_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
