# Generated by Django 5.2.4 on 2025-08-10 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_loteproducto_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertaproducto',
            name='precio_venta_base',
        ),
    ]
