# Generated by Django 5.2.1 on 2025-06-05 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_loteproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_vencimiento',
        ),
    ]
