# Generated by Django 5.2.4 on 2025-08-18 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_remove_ofertaproducto_precio_venta_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la obligación/recordatorio', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la obligación')),
                ('tipo_obligacion', models.CharField(choices=[('fija', 'Obligación Fija'), ('variable', 'Obligación Variable'), ('acuerdo', 'Basada en Acuerdo')], default='variable', max_length=20)),
                ('periodicidad', models.CharField(blank=True, choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('bianual', 'Bianual')], max_length=20)),
                ('dia_mes', models.PositiveIntegerField(blank=True, help_text='Día del mes (1-31)', null=True)),
                ('mes_anio', models.PositiveIntegerField(blank=True, help_text='Mes del año (1-12)', null=True)),
                ('fecha_primera_ejecucion', models.DateField(help_text='Primera fecha de ejecución/recordatorio')),
                ('fecha_ultima_ejecucion', models.DateField(blank=True, null=True)),
                ('proxima_fecha_ejecucion', models.DateField(help_text='Próxima fecha de ejecución')),
                ('dias_anticipacion_alerta', models.PositiveIntegerField(default=5, help_text='Días antes para enviar alerta')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='inventario.empresa')),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
                'ordering': ['proxima_fecha_ejecucion'],
            },
        ),
    ]
