# Generated by Django 5.2.4 on 2025-09-07 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_recordatorio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='region',
        ),
    ]
