# Generated by Django 5.2.1 on 2025-06-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_remove_producto_fecha_vencimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
    ]
