# Generated by Django 5.2.4 on 2025-09-30 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_remove_proveedor_comuna_remove_proveedor_direccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='dramage',
            new_name='gramage',
        ),
    ]
