# Generated by Django 5.2.1 on 2025-06-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Seleccione la categoría', 'Seleccione la categoría'), ('Alimentos Secos', 'Alimentos Secos'), ('Aliemntos Frescos', 'Alimentos Frescos'), ('Bebidas', 'Bebidas'), ('Lacteos', 'Lácteos'), ('Congelados', 'Congelados'), ('Dulcería & Confitería', 'Dulcería & Confitería'), ('Mascotas', 'Mascotas'), ('Belleza', 'Belleza'), ('Aseo del Hogar', 'Aseo del Hogar'), ('Aseo Personal', 'Aseo Personal'), ('Misceláneos', 'Misceláneos'), ('Papelería & Oficina', 'Papelería & Oficina'), ('Electrónica Menor', 'Electrónica Menor'), ('Temporada / Festivos', 'Temporada / Festivos'), ('Fiambres', 'Fiambres')], default='Seleccione la categoría', help_text='Seleccione la categoría del producto.', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('Seleccione la unidad', 'Seleccione la unidad'), ('Unidad', 'Unidad'), ('Litro', 'Litro'), ('Kilogramo', 'Kilogramo'), ('Gramo', 'Gramo'), ('Mililitro', 'Mililitro'), ('Centímetro', 'Centímetro'), ('Caja', 'Caja'), ('Paquete', 'Paquete'), ('Docena', 'Docena'), ('Bolsa', 'Bolsa'), ('Centímetro', 'Centímetro')], default='Seleccione la unidad', help_text='Seleccione la unidad de medida del producto.', max_length=50),
        ),
    ]
