# Generated by Django 5.2.4 on 2025-10-22 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_rename_dramage_producto_gramage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='gramage',
            new_name='gramaje',
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_sku_digits', message='El SKU debe contener solo números (sin espacios).', regex='^\\d+$')]),
        ),
    ]
