# Generated by Django 5.2.4 on 2025-10-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_rename_gramage_producto_gramaje_alter_producto_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaproducto',
            name='min_step_grams',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='ofertaproducto',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ofertaproducto',
            name='sell_by_weight',
            field=models.BooleanField(default=False),
        ),
    ]
