# Generated by Django 5.2.1 on 2025-06-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_producto_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
    ]
