# Generated by Django 5.2.4 on 2025-11-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventario', '0016_ofertaproducto_min_step_grams_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='almacenero',
            options={},
        ),
        migrations.AlterField(
            model_name='almacenero',
            name='run',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('abarrotes', 'Abarrotes'), ('cereales_legumbres', 'Cereales y Legumbres'), ('aceites_vinagres', 'Aceites y Vinagres'), ('conservas', 'Conservas y Enlatados'), ('especias_condimentos', 'Especias y Condimentos'), ('reposteria', 'Repostería y Postres'), ('frutas_verduras', 'Frutas y Verduras'), ('carniceria', 'Carnicería'), ('pollo_granel', 'Pollo al Granel'), ('pescados_mariscos', 'Pescados y Mariscos'), ('panaderia', 'Panadería'), ('lacteos_huevos', 'Lácteos y Huevos'), ('embutidos', 'Embutidos'), ('congelados', 'Congelados'), ('bebidas', 'Bebidas'), ('aguas', 'Aguas y Jugos'), ('cervezas', 'Cervezas'), ('licores', 'Licores y Vinos'), ('snacks', 'Snacks y Dulces'), ('helados', 'Helados'), ('limpieza', 'Artículos de Limpieza'), ('cuidado_personal', 'Cuidado Personal'), ('papeleria', 'Papelería e Higiene'), ('hogar', 'Artículos de Hogar'), ('mascotas', 'Productos para Mascotas'), ('ferreteria_basica', 'Ferretería Básica'), ('bazar', 'Bazar y Misceláneos')], max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='almacenero',
            constraint=models.UniqueConstraint(
                fields=('run',),
                name='uniq_almacenero_run_not_null',
                condition=~models.Q(run__isnull=True),
            ),
        ),
    ]
