# Generated by Django 5.2.1 on 2025-06-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_detalleorden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenventa',
            name='observacion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ordenventa',
            name='total_productos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
