# Generated by Django 5.2.3 on 2025-07-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'ordering': ['-fecha_envio'], 'verbose_name': 'Mensaje de Contacto', 'verbose_name_plural': 'Mensajes de Contacto'},
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
