# Generated by Django 5.2.4 on 2025-10-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_contacto_options_alter_contacto_fecha_envio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='correo_electronico',
            new_name='email',
        ),
        migrations.AddField(
            model_name='contacto',
            name='empresa',
            field=models.CharField(default='almacen_temporal', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(default='0', max_length=9),
            preserve_default=False,
        ),
    ]
