from django.urls import path
from .views import (
    home, seleccionar_plan, logout_view, perfil, inventario_view,
    agregar_producto, editar_producto, eliminar_producto,
    agregar_lote_producto, detalle_producto, editar_lote, eliminar_lote,
    retirar_lote, buscar_producto_api, verificar_producto_api, 
    obtener_datos_sku_api, agregar_proveedor, lista_recordatorios, agregar_recordatorio, 
    editar_recordatorio, eliminar_recordatorio, completar_recordatorio, descontar_producto_view, 
    metrics_view, flujo_opciones, producto_resumen, post_creacion_producto, ajustar_stock,
    salida_cecina_por_monto_view, post_login_router, onboarding_inicial
)

urlpatterns = [
    path('home/', home, name='home'),
    path('planes/seleccionar/<int:plan_id>/', seleccionar_plan, name='seleccionar_plan'),
    path('logout/', logout_view, name='logout'),
    path('perfil/', perfil, name='perfil'),
    path('inventario/', inventario_view, name='inventario'),
    path('productos/agregar/', agregar_producto, name='agregar-producto'),
    path('productos/editar/<int:producto_id>/', editar_producto, name='editar_producto'),
    path('productos/eliminar/<int:producto_id>/', eliminar_producto, name='eliminar_producto'),
    path('lotes/agregar/', agregar_lote_producto, name='agregar_lote'),
    path('productos/<int:producto_id>/lotes/', detalle_producto, name='detalle_producto'),
    path('lotes/<int:lote_id>/editar/', editar_lote, name='editar_lote'),
    path('lotes/<int:lote_id>/eliminar/', eliminar_lote, name='eliminar_lote'),
    path('lotes/<int:lote_id>/retirar/', retirar_lote, name='retirar_lote'),
    path('api/buscar-producto/<str:codigo_barras>/', buscar_producto_api, name='buscar_producto_api'),
    path('api/verificar-producto/<str:codigo_barras>/', verificar_producto_api, name='verificar_producto_api'),
    path('api/obtener-datos-sku/<str:sku>/', obtener_datos_sku_api, name='obtener_datos_sku_api'),
    path('proveedores/agregar/', agregar_proveedor, name='agregar_proveedor'),
    path('recordatorios/', lista_recordatorios, name='lista_recordatorios'),
    path('recordatorios/agregar/', agregar_recordatorio, name='agregar_recordatorio'),
    path('recordatorios/<int:recordatorio_id>/editar/', editar_recordatorio, name='editar_recordatorio'),
    path('recordatorios/<int:recordatorio_id>/eliminar/', eliminar_recordatorio, name='eliminar_recordatorio'),
    path('recordatorios/<int:recordatorio_id>/completar/', completar_recordatorio, name='completar_recordatorio'),
    path('descontar-producto/', descontar_producto_view, name='descontar_producto'),
    path("metrics/", metrics_view, name="metrics"),
    path('flujo/opciones/<int:producto_id>/', flujo_opciones, name='flujo_opciones'),
    path('productos/resumen/<int:producto_id>/', producto_resumen, name='producto_resumen'),
    path('productos/post-creacion/<int:producto_id>/', post_creacion_producto, name='post_creacion_producto'),
    path('inventario/ajustar-stock/<int:producto_id>/', ajustar_stock, name='ajustar_stock'),
    path('inventario/salida-cecina-monto/', salida_cecina_por_monto_view, name='salida_cecina_monto'),
    path("post-login/", post_login_router, name="post_login_router"),
    path("onboarding/", onboarding_inicial, name="onboarding_inicial"),
]